import typescript from '@rollup/plugin-typescript';
import resolve from '@rollup/plugin-node-resolve';

const MIT_HEADER = `// Baramoji — MIT License
// Copyright (c) 2025 361do_sleep (original)
// Copyright (c) 2025 rebuildup and contributors (TypeScript port)
// Source: https://github.com/rebuildup/Ae_Baramoji_ts
//
// This file is auto-generated from src/entries/*.ts.
// Do not edit this file directly — modify the TypeScript source instead.
`;

const entries = [
  ['src/entries/Baramoji.ts', 'dist/Baramoji.jsx'],
  ['src/entries/Baramoji_txt.ts', 'dist/Baramoji_txt.jsx'],
  ['src/entries/Baramoji_txt_win.ts', 'dist/Baramoji_txt_win.jsx'],
  ['src/entries/Baramoji_shape.ts', 'dist/Baramoji_shape.jsx'],
  ['src/entries/Baramoji_shape_win.ts', 'dist/Baramoji_shape_win.jsx'],
  ['src/entries/Baramoji_part.ts', 'dist/Baramoji_part.jsx'],
  ['src/entries/Baramoji_part_win.ts', 'dist/Baramoji_part_win.jsx'],
];

export default entries.map(([input, output]) => ({
  input,
  output: {
    file: output,
    format: 'iife',
    name: null,
    extend: false,
    banner: MIT_HEADER,
    sourcemap: false,
    generatedCode: { constBindings: false },
  },
  plugins: [
    typescript({
      tsconfig: './tsconfig.json',
      compilerOptions: {
        noEmitOnError: false,
        sourceMap: false,
      },
      // include patterns are resolved relative to tsconfig.rootDir (./src),
      // so we keep the globs anchored to src/.
      include: ['**/*.ts', '**/*.tsx', '**/*.d.ts'],
    }),
    resolve({ extensions: ['.ts', '.tsx', '.js'] }),
  ],
}));